Fix SelectableText only supports TextSpan exception for Flutter 2
Cretezy/flutter_linkify pull request #80
Opened 2021-03-08 21:29 UTC by MohamedEL-Torky

Not much changed, Thanks for your hard work on this package anyway <3

2021-03-08 21:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Cretezy/flutter_linkify?pullRequest=80) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Cretezy/flutter_linkify?pullRequest=80) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Cretezy/flutter_linkify?pullRequest=80) it.</sub>

2021-04-07 01:08 UTC, bsneider commented
@Cretezy will this be merged?

2021-04-11 14:17 UTC, pr-Mais commented
Thanks for this fix, I had to use this PR's fork in my project to solve this exception, waiting for it to be merged.

2021-04-12 18:20 UTC, Cretezy requested changes

2021-04-12 18:20 UTC, Cretezy commented on lib/flutter_linkify.dart
> -          child: MouseRegion(
It seems like we would like to keep `MouseRegion` support for the non-selecting use-case.

I think having `SelectableLinkify` pass an argument to `buildTextSpan` to not use `MouseRegion` would be a better implementation.

2021-04-12 19:58 UTC, MohamedEL-Torky commented on lib/flutter_linkify.dart
> -          child: MouseRegion(
@Cretezy 
Unfortunately adding `LinkableSpan` class as a wrapper to support `MouseRegion` will result in throwing the following error for anyone who uses flutter 2 
`"SelectableText only supports TextSpan; Other types of InlineSpan is not allowed"`

Prior Flutter 2 the selectable_text.dart class was declaring the rich text inside the class as dynamic type, but after flutter 2 the type was enforced to be TextSpan that's why the assertion is throwing an error.

on line 230 inside selectable_text.dart file after Flutter 2.0

```
  const SelectableText.rich(
    TextSpan this.textSpan, {
    Key? key,
    this.focusNode,
    this.style,
    this.strutStyle,
```

on line 253 inside selectable_text.dart file before Flutter 2 

```
  const SelectableText.rich(
    this.textSpan, {
    Key key,
    this.focusNode,
    this.style,
    this.strutStyle,
```

So we can't use WidgetSpan to enable using the MouseRegion region property.

There is a merge request on Flutter repo for letting the TextSpan widget support mouseCursor and it was accepted but it was merged on the master channel only.

https://github.com/flutter/flutter/pull/77754

2021-04-12 20:00 UTC, Cretezy commented on lib/flutter_linkify.dart
> -          child: MouseRegion(
I believe you misunderstood me.

When rendering `Linkify`, we can use mouse regions, therefore we should. When rendering `SelectableLinkify`, we can't use mouse regions, therefore we shouldn't.

The argument should toggle between using mouse regions and not. `Linkify` should have it as `true` while `SelectableLinkify` should have it as `false`.

2021-04-12 20:27 UTC, MohamedEL-Torky commented on lib/flutter_linkify.dart
> -          child: MouseRegion(
@Cretezy 

Sorry for the misunderstanding.
I have updated the pull request, please review the updates.

2021-04-13 01:25 UTC, Cretezy approved these changes

2021-04-13 01:25 UTC, merged

2021-04-13 01:27 UTC, Cretezy commented
Thank you, just released 5.0.2 with this change!